# This workflow will install Python dependencies, run tests and lint with a single version of Python.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install black
        run: pip install git+https://github.com/psf/black
      - name: Run black --check .
        run: black --check -l 100 .

  flake8:
    needs: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install flake8
        run: |
          pip install flake8
      - name: flake8
        run: |
          flake8 . --exclude=*.pyc,.github,__init__.py --max-line-length=100 --extend-ignore=W605,F401,F811,E203 --statistics

  pylint:
    needs: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install pylint
        run: |
          pip install pylint
      - name: PyLint
        run: |
          pylint ./**/*.py *.py --rcfile ./config/pylint.cfg --fail-under 10 --ignore-patterns=.github

  hadolint:
    name: Hadolint
    needs: [flake8, black]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Dockerfile: [Hadolint]
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          ignore: DL3008, DL3022
